#!/usr/bin/bash

# Main function
main() {
    input_file=$1

    while IFS= read -r number; do
        factors=$(factor "$number" | sed 's/: /=/; s/ /\*/g')
        echo "$factors"
    done < "$input_file"
}

main "$@"

